"""added doc images table

Revision ID: 68f541872f81
Revises: 567a499222a5
Create Date: 2020-12-02 14:28:28.969148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f541872f81'
down_revision = '567a499222a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagename', sa.String(), nullable=True),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accounts', sa.Column('email', sa.String(), nullable=False))
    op.drop_constraint('accounts_username_key', 'accounts', type_='unique')
    op.create_unique_constraint(None, 'accounts', ['email'])
    op.drop_column('accounts', 'username')
    op.add_column('documents', sa.Column('docname', sa.String(), nullable=True))
    op.drop_column('documents', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'docname')
    op.add_column('accounts', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'accounts', type_='unique')
    op.create_unique_constraint('accounts_username_key', 'accounts', ['username'])
    op.drop_column('accounts', 'email')
    op.drop_table('images')
    # ### end Alembic commands ###
