swagger: "2.0"
info:
  description: "This is a server to sort, change and convert md file to pdf format"
  version: "1.0.0"
  title: "AllInOneMD"
paths:
  /account:
    post:
      tags:
        - "login"
      summary: "add's a new account"
      operationId: "NewAccount"
      responses:
        "405":
          description: "Invalid input"
  /account/{AccountId}:
    get:
      tags:
        - "login"
      summary: "retrieve's account data"
      operationId: "LoginToAccount"
      parameters:
      - name: "AccountId"
        in: "path"
        description: "ID of account to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "405":
          description: "Invalid input"
  /document:
    post:
      tags:
         - "doc"
      summary: "make's new md document"
      operationId: "NewDoc"
      responses:
        "405":
          description: "Invalid input"
  /document/{DocumentId}:
    get:
      tags:
        - "doc"
      summary: "retrieve's md doc"
      operationId: "OpenDocument"
      parameters:
      - name: "DocumentId"
        in: "path"
        description: "ID of document to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "405":
          description: "Invalid input"
    patch:
      tags:
        - "doc"
      summary: "edit md document"
      operationId: "EditDocument"
      parameters:
      - name: "DocumentId"
        in: "path"
        description: "ID of document to edit"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "405":
          description: "Invalid input"
    delete:
      tags:
        - "doc"
      summary: "deletes md document"
      operationId: "DelDocument"
      parameters:
      - name: "DocumentId"
        in: "path"
        description: "ID of document to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "405":
          description: "Invalid input"
      